Update fi.json
citizenfx/txAdmin pull request #131
Opened 2020-05-22 14:56 UTC by Jauska

2020-05-22 23:28 UTC, MatiasFI requested changes
`"instruction": "Pidä Välilyöntiä pohjassa 10 sekunttia jatkaaksesi."`
->
`"instruction": "Pidä välilyöntiä pohjassa 10 sekuntia jatkaaksesi."`

2020-05-23 02:54 UTC, tabarra commented
@Jauska and @MatiasFI, can you guys please sort it out which one is the right translation so I can merge this before Sunday?  
Thank you very much.

2020-05-23 05:16 UTC, Jauska commented
It seems that i made a typo and Matias fixed it.

2020-05-23 08:28 UTC, tabarra approved these changes

2020-05-23 08:28 UTC, merged