Automatic WL cleanup of inactive players.
citizenfx/txAdmin pull request #149
Opened 2020-06-01 21:29 UTC by SeaquestNet

Hi!

I added an option to turn on automatic WL cleaning of inactive players (amount of days can be set in settings). We have this functionality on our server in our current whitelisting script but we wanna merge over to txAdmin as soon as possible. 

My current concerns/questions:
- How often to run this, might suffice with once a day?
- Is the "cronjob" section the correct way of running it?
- When removing whitelist from a player, i'm currently revoking the whitelist action. However I am also removing the player object from the database (otherwise the same player would be polled over and over again). Good or bad?

Would you have a look at it and give me some pointers/thoughts?

2020-06-02 20:21 UTC, SeaquestNet commented
Added cleanup functionality to checkPlayerJoin function. Left my original code for now but will clean that up once we settle on a final solution.

What do you think?

2020-06-07 09:59 UTC, SeaquestNet commented
Did you get a chance to take a look at this?

2020-06-08 03:55 UTC, tabarra commented
Unfortunately not yet

2020-08-09 21:59 UTC, SeaquestNet commented
Can we solve this by any chance? The server im developing for is looking to merge the whitelist to txAdmin but we can't do this without this feature. 

Thoughts?

2020-12-13 19:08 UTC, rdlh commented on locale/fr.json
> +        "whitelist_expired": "You have been inactive for too long and your whitelist has expired."
`Vous avez été inactif trop longtemps, votre whitelist est arrivée à expiration.`

2021-01-17 18:30 UTC, lze3 requested changes

2021-01-17 18:30 UTC, lze3 commented on src/components/playerController/index.js
> +                    let idArray = [];
Can be `const`, you don't reassign its value.
```suggestion
                    const idArray = [];
```

2021-01-17 18:30 UTC, lze3 commented on src/components/playerController/index.js
> +                    let player = await this.dbo.get('players').find({license: license}).value();
ditto
```suggestion
                    const license = idArray.find((id) => id.substring(0, 8) == "license:").substring(8);
                    const player = await this.dbo.get('players').find({license: license}).value();
```

2021-10-03 19:57 UTC, tabarra commented
For merging this I was first waiting for the "database cleanup page", and it is [finally done](https://i.imgur.com/bfjjnOP.png).  
But after over a year things changed too much :(  
  
This will still be a thing somewhen.  
Thank you for your PR.

2021-10-03 19:57 UTC, closed without merging