feat(menu/player-modal): Allow usernames in txadmin command
citizenfx/txAdmin pull request #452
Opened 2021-09-26 15:48 UTC by Poggicek

/tx or /txadmin will now accept usernames with ids, if multiple clients with similiar names are found it will fill out the search input with the arguments from txadmin command and list all similiar names. Unless the search input is modified it will be cleared when the menu gets closed.

2021-09-26 16:06 UTC, TasoOneAsia requested changes
Before in-game testing

2021-09-26 16:06 UTC, TasoOneAsia commented on locale/en.json
> +                "target_not_found": "Was unable to find an online player with ID %{target}"
Since this can now be a name or ID this phrase won't work for a name.

2021-09-26 16:06 UTC, TasoOneAsia commented on menu/src/MenuWrapper.tsx
>    }, [visible]);
Missing dependent state in dep array. The setter function is stable and can be ignored from deps.

```suggestion
  }, [visible, playersFilterIsTemp]);
```

2021-09-26 16:06 UTC, TasoOneAsia commented on menu/src/hooks/useHudListenersService.tsx
> +      if (foundPlayers.length == 1)
```suggestion
      if (foundPlayers.length === 1)
```

2021-09-26 16:06 UTC, TasoOneAsia commented on scripts/menu/client/cl_base.lua
> +    if isMenuVisible and #args >= 1 then
Guess this is being done to handle names with spaces in them?

2021-09-26 16:06 UTC, TasoOneAsia commented on menu/src/hooks/useHudListenersService.tsx
> +    let targetId = parseInt(target)
Not reassigned anywhere.
```suggestion
    const targetId = parseInt(target)
```

2021-09-26 16:06 UTC, TasoOneAsia commented on menu/src/state/players.state.ts
> +
```suggestion
```

2021-09-26 16:31 UTC, Poggicek commented on scripts/menu/client/cl_base.lua
> +    if isMenuVisible and #args >= 1 then
yes

2021-09-27 23:41 UTC, TasoOneAsia approved these changes
Small change and all good from me.

2021-09-27 23:41 UTC, TasoOneAsia commented on locale/en.json
> +                "target_not_found": "Was unable to find an online player with ID or an username %{target}"
```suggestion
                "target_not_found": "Was unable to find an online player with ID or an username of %{target}"
```

2021-09-28 00:29 UTC, merged

2021-10-05 14:07 UTC, tabarra commented
You guys didn't update the chat suggestion? 🤦‍♂️

2021-10-05 16:43 UTC, TasoOneAsia commented
Apparently not 🤔, oh well